---
- name: Install Terraform using Ansible
  hosts: all
  become: true
  tasks:

    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - software-properties-common
          - wget
        state: present
        update_cache: true

    - name: Ensure /usr/share/keyrings directory exists
      ansible.builtin.file:
        path: /usr/share/keyrings
        state: directory
        mode: '0755'

    - name: Download and add HashiCorp GPG key
      ansible.builtin.get_url:
        url: https://apt.releases.hashicorp.com/gpg
        dest: /usr/share/keyrings/hashicorp-archive-keyring.gpg
        mode: '0644'

    - name: Add HashiCorp repository
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/hashicorp.list
        line: "deb [arch={{ ansible_architecture }} signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        mode: '0644'
        create: true

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install Terraform
      ansible.builtin.apt:
        name: terraform
        state: present
