name: Ansible Syntax Check

on:
  push:
    branches:
      - main
      - dev

jobs:
  syntax-check:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install -q ansible ansible-lint

    - name: Ansible syntax check
      run: ansible-playbook --syntax-check -i inventries/inventory.yml playbooks/*.yml

    - name: Ansible lint check
      run: ansible-lint playbooks/*.yml
